"""The model a request names is the model that generates it (and /ready tells the truth).

Before this, ``MLXProvider`` served ``self.model_id`` whatever ``GenRequest.model`` said and
the gateway's ``ModelManager`` factory returned the SAME provider for every id. So the /chat
dropdown, the ``model`` field of ``/v1/chat/completions`` and ``/v1/hearth/agent``, and every
per-class rung of ``config/routing.finance.yaml`` were generated by the default model — and
``/v1/hearth/admin/ready`` said 200 with no weights loaded at all.

These tests assert on the OUTCOME (CLAUDE.md §3), never on what a response says about
itself: the fake ``mlx_lm`` below records the exact path every ``load()`` read and tags every
generated token with the weights that produced it, so "generated BY X" is a property of the
text, not of a telemetry field that could be filled in from the request.
"""

from __future__ import annotations

import importlib.machinery
import json
import os
import subprocess
import sys
import threading
import time
import types
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from typer.testing import CliRunner

from hearth import providers as providers_pkg
from hearth.config import Settings
from hearth.gateway import create_app
from hearth.observability.budget import BudgetAccountant
from hearth.observability.metrics import MetricsStore
from hearth.providers import mlx as mlx_mod
from hearth.providers import mlx_pool
from hearth.providers.base import GenRequest, Message, StreamDelta
from hearth.providers.mlx import MLXProvider, ModelMismatchError, ModelNotOnDiskError
from hearth.registry import get_registry
from hearth.router import ProviderError, Router
from hearth.router.policy import load_policy
from hearth.serving import ModelPool, UnknownModelError

SMALL = "mlx-community/Qwen2.5-3B-Instruct-4bit"  # registry ram_gb 2.0
CODER7 = "mlx-community/Qwen2.5-Coder-7B-Instruct-4bit"  # registry default, ram_gb 4.5
BIG = "mlx-community/Qwen2.5-14B-Instruct-4bit"  # ram_gb 9.0
EMBED = "mlx-community/bge-small-en-v1.5-bf16"
FINANCE_YAML = Path(__file__).resolve().parents[1] / "config" / "routing.finance.yaml"


def weights(model_id: str) -> str:
    """The on-disk path the fake resolver hands mlx_lm.load for ``model_id``."""
    return f"/weights/{model_id}"


def tag(model_id: str) -> str:
    """The marker every token generated by ``model_id``'s weights carries."""
    return f"<<{weights(model_id)}>>"


# -- a fake mlx_lm that cannot lie about which weights ran ---------------------------------


class _Tokenizer:
    eos_token = "<|im_end|>"

    def encode(self, text):
        return list(text)

    def apply_chat_template(self, chat, tokenize, add_generation_prompt):
        return chat[-1]["content"]


class _Weights:
    def __init__(self, path: str) -> None:
        self.path = path


class _Response:
    def __init__(self, text: str, finish_reason: str | None = None) -> None:
        self.text = text
        self.finish_reason = finish_reason


class FakeMLX:
    """``load`` records the path it read; ``stream_generate`` tags output with that path."""

    def __init__(self) -> None:
        self.loads: list[tuple[str, str]] = []  # (path, thread name)
        self.generations: list[tuple[str, str]] = []
        self.missing: set[str] = set()
        self.load_gate: threading.Event | None = None
        self.reply = lambda path, prompt: f"<<{path}>>"

    def load(self, path, **kwargs):
        if self.load_gate is not None:
            assert self.load_gate.wait(10), "test never released the load"
        self.loads.append((path, threading.current_thread().name))
        return _Weights(path), _Tokenizer()

    def stream_generate(self, model, tokenizer, prompt, max_tokens):
        self.generations.append((model.path, threading.current_thread().name))
        text = self.reply(model.path, prompt)
        half = max(1, len(text) // 2)
        yield _Response(text[:half])
        yield _Response(text[half:], "stop")

    def resolve(self, model_id, allow_downloads=None):
        if model_id in self.missing:
            raise ModelNotOnDiskError(f"model {model_id!r} is not on disk")
        return weights(model_id)

    def loaded_paths(self) -> list[str]:
        return [p for p, _ in self.loads]

    def generated_paths(self) -> list[str]:
        return [p for p, _ in self.generations]


@pytest.fixture
def fake(monkeypatch) -> FakeMLX:
    fake = FakeMLX()
    module = types.ModuleType("mlx_lm")
    module.load = fake.load
    module.stream_generate = lambda *a, **k: fake.stream_generate(*a, **k)
    module.__spec__ = importlib.machinery.ModuleSpec("mlx_lm", loader=None)
    monkeypatch.setitem(sys.modules, "mlx_lm", module)
    monkeypatch.setattr(mlx_mod, "resolve_local_model", fake.resolve)
    # The readiness disk probe: the fake's paths are not real directories, so its "on disk"
    # is the fake resolver's answer (the real probe's exists-check is tested on its own).
    monkeypatch.setattr(providers_pkg, "_locate_on_disk", fake.resolve)
    monkeypatch.delenv("HEARTH_DEFAULT_MODEL", raising=False)
    monkeypatch.delenv("HEARTH_ROUTING_YAML", raising=False)
    return fake


def _settings(tmp_path, **kw) -> Settings:
    base = dict(
        backend="mlx", home=tmp_path / ".hearth", require_auth=False, warmup=False,
        ram_ceiling_gb=24.0,
    )
    base.update(kw)
    return Settings(**base)


def _router(provider, policy) -> Router:
    return Router(
        local_provider=provider,
        policy=policy,
        budget=BudgetAccountant(policy.defaults.remote_budget_tokens_per_day),
        metrics=MetricsStore(),
    )


def _app(tmp_path, policy, **kw):
    settings = _settings(tmp_path, **kw)
    pool = mlx_pool(settings)
    router = _router(pool, policy)
    return create_app(provider=pool, settings=settings, router=router), pool, router


def _records(router):
    return list(router.metrics._records)  # MetricsStore has no public listing


def _chat(client, model, text="hello", stream=False, **extra):
    body = {"model": model, "messages": [{"role": "user", "content": text}], "stream": stream}
    body.update(extra)
    return client.post("/v1/chat/completions", json=body)


def _sse_events(resp) -> list:
    out = []
    for line in resp.text.splitlines():
        if line.startswith("data: "):
            payload = line[len("data: "):]
            out.append(payload if payload == "[DONE]" else json.loads(payload))
    return out


def _stream_text_and_final(resp):
    events = [e for e in _sse_events(resp) if e != "[DONE]"]
    text = "".join(
        (c["choices"][0]["delta"].get("content") or "") for c in events if "choices" in c
    )
    final = next(e for e in reversed(events) if e.get("hearth"))
    return text, final


# -- a request for model X is generated BY X -----------------------------------------------


def test_non_streaming_request_is_generated_by_the_named_model(fake, tmp_path, local_policy):
    app, _, router = _app(tmp_path, local_policy)
    client = TestClient(app)
    for model in (SMALL, CODER7, SMALL):
        body = _chat(client, model).json()
        assert body["choices"][0]["message"]["content"] == tag(model)  # the weights that ran
        assert body["hearth"]["model"] == model
    assert fake.generated_paths() == [weights(SMALL), weights(CODER7), weights(SMALL)]
    # Each model's weights were read exactly once — the pool kept both resident.
    assert sorted(fake.loaded_paths()) == sorted([weights(SMALL), weights(CODER7)])
    assert [r.model for r in _records(router)] == [SMALL, CODER7, SMALL]


def test_streaming_request_is_generated_by_the_named_model(fake, tmp_path, local_policy):
    app, _, router = _app(tmp_path, local_policy)
    client = TestClient(app)
    for model in (SMALL, CODER7):
        text, final = _stream_text_and_final(_chat(client, model, stream=True))
        assert text == tag(model)
        assert final["hearth"]["model"] == model
        assert final["model"] == model
    assert fake.generated_paths() == [weights(SMALL), weights(CODER7)]
    assert [r.model for r in _records(router)] == [SMALL, CODER7]


def test_auto_is_the_registry_default(fake, tmp_path, local_policy):
    app, _, _ = _app(tmp_path, local_policy)
    body = _chat(TestClient(app), "auto").json()
    assert body["choices"][0]["message"]["content"] == tag(get_registry().default_id)


def test_concurrent_mixed_requests_each_get_their_own_weights(fake, tmp_path, local_policy):
    """3B and 7B, streaming and not, from many request threads at once."""
    app, _, _ = _app(tmp_path, local_policy)
    client = TestClient(app)
    jobs = [(SMALL if i % 2 else CODER7, bool(i % 3 == 0)) for i in range(16)]

    def run(job):
        model, stream = job
        if stream:
            text, final = _stream_text_and_final(_chat(client, model, f"q{model}", stream=True))
            return model, text, final["hearth"]["model"]
        body = _chat(client, model, f"q{model}").json()
        return model, body["choices"][0]["message"]["content"], body["hearth"]["model"]

    with ThreadPoolExecutor(max_workers=8) as pool:
        results = list(pool.map(run, jobs))
    for model, text, reported in results:
        assert text == tag(model)
        assert reported == model
    # Every load and every generation ran on the one MLX thread (thread-local GPU stream).
    threads = {t for _, t in fake.loads} | {t for _, t in fake.generations}
    assert len(threads) == 1 and next(iter(threads)).startswith("hearth-mlx")
    assert len(fake.generations) == len(jobs)


def test_streaming_telemetry_comes_from_the_provider_that_ran(tmp_path, local_policy):
    """A provider that answers with other weights is reported as such, not as the request.

    Before, the final SSE chunk and the RequestRecord carried ``decision.model`` — the model
    that was ASKED for — so a stream served by the wrong weights still reported the right
    name. A provider that ignores the requested id exposes exactly that.
    """

    class StubbornProvider:
        name = "stubborn"

        def capabilities(self):
            return None

        def generate(self, req):
            raise AssertionError("streaming test")

        def stream(self, req):
            yield "x"

        def stream_deltas(self, req):
            yield StreamDelta(text="answer")
            yield StreamDelta(finish_reason="stop", model="the-weights-that-actually-ran")

        def footprint(self, model_id):
            return None

    provider = StubbornProvider()
    router = _router(provider, local_policy)
    settings = Settings(backend="echo", home=tmp_path / "h", require_auth=False, warmup=False)
    client = TestClient(create_app(provider=provider, settings=settings, router=router))
    _, final = _stream_text_and_final(_chat(client, SMALL, stream=True))
    assert final["hearth"]["model"] == "the-weights-that-actually-ran"
    assert _records(router)[-1].model == "the-weights-that-actually-ran"


# -- the per-class ladder sends classify to the small model ---------------------------------


def test_finance_ladder_sends_classify_to_the_small_model(fake, tmp_path):
    policy = load_policy(FINANCE_YAML)
    pool = mlx_pool(_settings(tmp_path))
    router = _router(pool, policy)

    def ask(intent):
        req = GenRequest(messages=[Message(role="user", content="Coffee 4.50")], model="auto")
        return router.route(req, intent=intent, allow_escalation=False)

    classify = ask("classify")
    assert classify.result.text == tag(SMALL)
    assert classify.result.model == SMALL
    summarize = ask("summarize")
    assert summarize.result.text == tag(BIG)
    assert summarize.result.model == BIG
    assert fake.generated_paths() == [weights(SMALL), weights(BIG)]


def test_finance_ladder_through_the_gateway_stream(fake, tmp_path):
    app, _, _ = _app(tmp_path, load_policy(FINANCE_YAML))
    resp = _chat(TestClient(app), "auto", "Coffee 4.50", stream=True,
                 hearth={"intent": "classify"})
    text, final = _stream_text_and_final(resp)
    assert text == tag(SMALL)
    assert final["hearth"]["model"] == SMALL


def test_mcp_tools_follow_the_ladder(fake, tmp_path, monkeypatch):
    from hearth.mcp.tools import build_toolset

    settings = _settings(tmp_path)
    tools = build_toolset(settings=settings, router=_router(mlx_pool(settings),
                                                            load_policy(FINANCE_YAML)))
    assert tools.summarize("a long statement") == tag(BIG)
    assert fake.generated_paths() == [weights(BIG)]


def test_mcp_default_toolset_is_multi_model(fake, tmp_path):
    from hearth.mcp.tools import build_toolset

    tools = build_toolset(settings=_settings(tmp_path))
    assert isinstance(tools.router.local, ModelPool)


# -- an unknown id is an error, never the default ----------------------------------------


@pytest.mark.parametrize("model", ["no/such-model", EMBED, "echo"])
@pytest.mark.parametrize("stream", [False, True])
def test_unknown_or_unservable_model_is_a_404(fake, tmp_path, local_policy, model, stream):
    app, _, _ = _app(tmp_path, local_policy)
    resp = _chat(TestClient(app), model, stream=stream)
    assert resp.status_code == 404
    err = resp.json()["error"]
    assert err["code"] == "model_not_found" and err["param"] == "model"
    assert model in err["message"]
    assert fake.loads == [] and fake.generations == []  # nothing was served instead


def test_agent_route_unknown_model_is_a_404(fake, tmp_path, local_policy):
    app, _, _ = _app(tmp_path, local_policy, file_roots=str(tmp_path))
    resp = TestClient(app).post("/v1/hearth/agent", json={"task": "t", "model": "nope/x"})
    assert resp.status_code == 404
    assert resp.json()["error"]["code"] == "model_not_found"
    assert fake.generations == []


def test_router_raises_unknown_model_not_a_provider_error(fake, tmp_path, local_policy):
    router = _router(mlx_pool(_settings(tmp_path)), local_policy)
    req = GenRequest(messages=[Message(role="user", content="x")], model="nope/x")
    with pytest.raises(UnknownModelError):
        router.route(req, allow_escalation=False)
    assert not isinstance(UnknownModelError("x", "y"), ProviderError)


def test_a_bare_provider_refuses_a_different_registered_model(fake):
    with pytest.raises(ModelMismatchError):
        MLXProvider(CODER7).generate(
            GenRequest(messages=[Message(role="user", content="x")], model=SMALL)
        )
    assert fake.generations == []


# -- the agent route and CLI serve the named model -----------------------------------------


def test_agent_route_steps_are_generated_by_the_named_model(fake, tmp_path, local_policy):
    fake.reply = lambda path, prompt: json.dumps({"thought": "t", "answer": f"<<{path}>>"})
    app, _, _ = _app(tmp_path, local_policy, file_roots=str(tmp_path))
    resp = TestClient(app).post("/v1/hearth/agent", json={"task": "say hi", "model": SMALL})
    events = [e for e in _sse_events(resp) if e != "[DONE]"]
    steps = [e for e in events if "index" in e]
    final = events[-1]
    assert final["answer"] == tag(SMALL)
    assert steps and all(s["model"] == SMALL for s in steps)
    assert fake.generated_paths() == [weights(SMALL)]


def test_cli_run_serves_the_named_model_and_refuses_unknown(fake, tmp_path, monkeypatch):
    from hearth import cli
    from hearth.config import get_settings

    monkeypatch.setenv("HEARTH_BACKEND", "mlx")
    monkeypatch.setenv("HEARTH_HOME", str(tmp_path / ".hearth"))
    monkeypatch.setenv("HEARTH_ROUTING_YAML", str(FINANCE_YAML))
    from hearth.router.policy import get_policy

    get_settings.cache_clear()
    get_policy.cache_clear()
    try:
        runner = CliRunner()
        ok = runner.invoke(cli.app, ["run", "--model", SMALL, "hello"])
        assert ok.exit_code == 0, ok.output
        assert tag(SMALL) in ok.stdout
        laddered = runner.invoke(cli.app, ["run", "--intent", "summarize", "hello"])
        assert laddered.exit_code == 0, laddered.output
        assert tag(BIG) in laddered.stdout  # "auto" now reaches the ladder
        bad = runner.invoke(cli.app, ["run", "--model", "nope/x", "hello"])
        assert bad.exit_code == 2
        assert "Unknown model" in bad.stdout
    finally:
        get_settings.cache_clear()
        get_policy.cache_clear()
    assert fake.generated_paths() == [weights(SMALL), weights(BIG)]


# -- eviction under the RAM ceiling --------------------------------------------------------


def test_lru_eviction_drops_the_weights_and_a_return_reloads_them(fake, tmp_path, monkeypatch):
    unload_threads: list[str] = []
    real_unload = MLXProvider._unload_here

    def spy(self):
        unload_threads.append(threading.current_thread().name)
        real_unload(self)

    monkeypatch.setattr(MLXProvider, "_unload_here", spy)
    pool = mlx_pool(_settings(tmp_path, ram_ceiling_gb=6.0))  # 4.5 + 2.0 > 6.0
    req = lambda m: GenRequest(messages=[Message(role="user", content="x")], model=m)  # noqa: E731

    assert pool.generate(req(CODER7)).text == tag(CODER7)
    coder = pool.manager.peek(CODER7)
    assert coder.is_loaded
    assert pool.generate(req(SMALL)).text == tag(SMALL)
    assert pool.manager.resident_ids() == [SMALL]
    assert pool.manager.resident_ram_gb() <= 6.0
    assert coder.is_loaded is False  # its weights were actually dropped, not just forgotten
    assert unload_threads and all(t.startswith("hearth-mlx") for t in unload_threads)
    assert pool.generate(req(CODER7)).text == tag(CODER7)
    assert fake.loaded_paths() == [weights(CODER7), weights(SMALL), weights(CODER7)]


_CHURN_CHILD = "HEARTH_TEST_CHURN_CHILD"
_CHURN_TIMEOUT_S = 60


def test_concurrent_churn_never_holds_weights_outside_the_ceiling(fake, tmp_path):
    """Pick-a-model and generate are one MLX job, so eviction cannot land between them.

    If the residency lookup ran on the request thread and only generation hopped to the MLX
    thread, an eviction could run in the gap and the generation would quietly reload the
    evicted weights outside the manager's accounting — RAM over the ceiling with every
    counter saying otherwise. Asserted two ways: every residency decision ran on the MLX
    thread, and at the end no provider holds weights the manager does not count.

    That mutant can also DEADLOCK (a request thread holds the manager's load lock while
    waiting on an MLX-thread unload; the MLX thread waits for the load lock). The MLX thread
    is process-global and non-daemon, so a thread + join(timeout) here would report the
    failure and then hang the next MLX test and interpreter exit. The body therefore runs
    in a child pytest with a hard timeout: a deadlock is a clean, attributed FAIL.
    """
    if os.environ.get(_CHURN_CHILD) != "1":
        node = f"{Path(__file__).resolve()}::{sys._getframe().f_code.co_name}"
        try:
            child = subprocess.run(
                [sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", node],
                env={**os.environ, _CHURN_CHILD: "1"},
                capture_output=True, text=True, timeout=_CHURN_TIMEOUT_S,
            )
        except subprocess.TimeoutExpired:
            pytest.fail(
                f"concurrent churn did not finish in {_CHURN_TIMEOUT_S}s — deadlock between "
                "the manager's load lock and the MLX thread"
            )
        assert child.returncode == 0 and "1 passed" in child.stdout, (
            child.stdout[-3000:] + child.stderr[-2000:]
        )
        return
    pool = mlx_pool(_settings(tmp_path, ram_ceiling_gb=6.0))  # only one of 7B/3B fits
    made: list[MLXProvider] = []
    real_factory = pool._factory

    def factory(model_id, ram_gb):
        made.append(real_factory(model_id, ram_gb))
        return made[-1]

    pool._factory = factory
    get_threads: list[str] = []
    real_get = pool.manager.get

    def spy_get(model_id):
        get_threads.append(threading.current_thread().name)
        return real_get(model_id)

    pool.manager.get = spy_get
    models = [CODER7 if i % 2 else SMALL for i in range(24)]

    def run(m):
        req = GenRequest(messages=[Message(role="user", content="x")], model=m)
        if m == SMALL:
            return m, "".join(d.text for d in pool.stream_deltas(req))
        return m, pool.generate(req).text

    with ThreadPoolExecutor(max_workers=8) as ex:
        for m, text in ex.map(run, models):
            assert text == tag(m)
    assert get_threads and all(t.startswith("hearth-mlx") for t in get_threads)
    resident = {id(p) for p in (r.provider for r in pool.manager.residents())}
    holding = [p.model_id for p in made if p.is_loaded and id(p) not in resident]
    assert holding == [], f"weights held outside the manager's accounting: {holding}"
    assert pool.manager.resident_ram_gb() <= 6.0


def test_two_models_stay_resident_when_they_fit(fake, tmp_path):
    pool = mlx_pool(_settings(tmp_path, ram_ceiling_gb=7.0))
    for m in (CODER7, SMALL, CODER7, SMALL):
        pool.generate(GenRequest(messages=[Message(role="user", content="x")], model=m))
    assert set(pool.manager.resident_ids()) == {CODER7, SMALL}
    assert len(fake.loads) == 2


def test_a_model_over_the_ceiling_is_refused_not_overcommitted(fake, tmp_path, local_policy):
    app, pool, _ = _app(tmp_path, local_policy, ram_ceiling_gb=6.0)
    resp = _chat(TestClient(app), BIG)  # 9 GB > 6 GB ceiling
    assert resp.status_code == 503
    assert fake.loads == []


# -- /ready is 503 until weights are loaded, and when the load fails -----------------------


def _wait_ready(client, want_status: str, timeout=5.0):
    deadline = time.monotonic() + timeout
    while True:
        resp = client.get("/v1/hearth/admin/ready")
        if resp.json()["status"] == want_status or time.monotonic() > deadline:
            return resp
        time.sleep(0.02)


def test_ready_is_503_until_the_weights_are_loaded(fake, tmp_path, local_policy):
    fake.load_gate = threading.Event()
    app, _, _ = _app(tmp_path, local_policy, warmup=True)
    client = TestClient(app)
    blocked = client.get("/v1/hearth/admin/ready")  # the load is parked in the fake
    assert blocked.status_code == 503
    assert blocked.json()["status"] == "loading"
    assert fake.loads == []
    fake.load_gate.set()
    ready = _wait_ready(client, "ready")
    assert ready.status_code == 200
    assert fake.loaded_paths() == [weights(CODER7)]  # the default's weights, really read


def test_without_warmup_ready_means_on_disk_and_the_first_request_loads_it(
    fake, tmp_path, local_policy
):
    """B-035: with HEARTH_WARMUP=false nothing loads until a request, and an orchestrator
    gating on /ready never sends one — so 503-until-loaded was 503 forever. Ready is now
    "the default's weights resolve on disk"; residency is reported separately."""
    app, _, _ = _app(tmp_path, local_policy, warmup=False)
    client = TestClient(app)
    resp = client.get("/v1/hearth/admin/ready")
    assert resp.status_code == 200, resp.json()
    assert resp.json()["status"] == "ready"
    assert resp.json()["loaded"] is False
    assert "first request" in resp.json()["detail"]
    assert fake.loads == []  # the probe itself loaded nothing
    assert _chat(client, "auto").json()["choices"][0]["message"]["content"] == tag(CODER7)
    resp = client.get("/v1/hearth/admin/ready")
    assert resp.status_code == 200 and resp.json()["loaded"] is True
    assert "detail" not in resp.json()


def test_without_warmup_a_default_not_on_disk_is_failed(fake, tmp_path, local_policy):
    fake.missing.add(CODER7)
    app, _, _ = _app(tmp_path, local_policy, warmup=False)
    resp = TestClient(app).get("/v1/hearth/admin/ready")
    assert resp.status_code == 503
    assert resp.json()["status"] == "failed"
    assert "not on disk" in resp.json()["reason"]


def test_without_warmup_a_failed_first_load_is_failed(fake, tmp_path, local_policy):
    def broken_load(path, **kwargs):
        raise RuntimeError("corrupt checkpoint")

    sys.modules["mlx_lm"].load = broken_load
    app, _, _ = _app(tmp_path, local_policy, warmup=False)
    client = TestClient(app)
    assert _chat(client, "auto").status_code == 503
    resp = client.get("/v1/hearth/admin/ready")
    assert resp.status_code == 503
    assert resp.json()["status"] == "failed"
    assert "corrupt checkpoint" in resp.json()["reason"]


def test_an_evicted_default_stays_ready_and_deleted_weights_do_not(fake, tmp_path, local_policy):
    """B-048: LRU eviction of the default made a healthy server report not-ready."""
    app, pool, _ = _app(tmp_path, local_policy, warmup=True, ram_ceiling_gb=6.0)
    client = TestClient(app)
    assert _wait_ready(client, "ready").json()["loaded"] is True
    assert _chat(client, SMALL).status_code == 200  # 2.0 + 4.5 > 6.0: evicts the default
    assert pool.manager.resident_ids() == [SMALL]
    resp = client.get("/v1/hearth/admin/ready")
    assert resp.status_code == 200, resp.json()
    assert resp.json()["loaded"] is False
    assert resp.json()["resident"] == [SMALL]
    assert "reloads on demand" in resp.json()["detail"]
    # ...and it really does reload on demand.
    assert _chat(client, "auto").json()["choices"][0]["message"]["content"] == tag(CODER7)
    assert fake.loaded_paths() == [weights(CODER7), weights(SMALL), weights(CODER7)]
    # Weights deleted from disk: no longer loadable, so no longer ready.
    _chat(client, SMALL)  # evict it again
    fake.missing.add(CODER7)
    resp = client.get("/v1/hearth/admin/ready")
    assert resp.status_code == 503
    assert resp.json()["status"] == "failed"
    assert "not on disk" in resp.json()["reason"]


def test_dropped_weights_are_reported_not_resident_and_reload(fake, tmp_path, local_policy):
    app, pool, _ = _app(tmp_path, local_policy)
    client = TestClient(app)
    pool.warm().unload()  # resident in the manager, but holding no weights
    resp = client.get("/v1/hearth/admin/ready")
    assert resp.status_code == 200
    assert resp.json()["loaded"] is False
    assert _chat(client, "auto").json()["choices"][0]["message"]["content"] == tag(CODER7)
    assert client.get("/v1/hearth/admin/ready").json()["loaded"] is True


def test_residency_without_weights_never_counts_as_loaded(fake, tmp_path, local_policy):
    """B-005 stays fixed: a provider admitted without weights in memory is not ready."""

    class NoWeights:
        name = "mlx"
        is_loaded = False

        def __init__(self, model_id, ram_gb):
            self.model_id = model_id

        def load(self, model_id=None):
            pass  # "loads" without holding anything

        def footprint(self, model_id):
            from hearth.providers.base import ResourceEstimate

            return ResourceEstimate(ram_gb=1.0)

    settings = _settings(tmp_path, warmup=True)
    pool = ModelPool(NoWeights, backend="mlx", ram_ceiling_gb=24.0, locate=fake.resolve)
    app = create_app(provider=pool, settings=settings, router=_router(pool, local_policy))
    resp = _wait_ready(TestClient(app), "failed")
    assert resp.status_code == 503
    assert "holds no weights" in resp.json()["reason"]
    assert pool.manager.loaded_once(CODER7) is False


def test_ready_reports_failure_when_the_default_is_not_on_disk(fake, tmp_path, local_policy):
    fake.missing.add(CODER7)
    app, _, _ = _app(tmp_path, local_policy, warmup=True)
    resp = _wait_ready(TestClient(app), "failed")
    assert resp.status_code == 503
    assert resp.json()["status"] == "failed"
    assert "not on disk" in resp.json()["reason"]


def test_ready_reports_a_default_model_override_nobody_can_serve(
    fake, tmp_path, local_policy, monkeypatch
):
    """B-047: the app refuses to be BUILT, so no part of it can serve 'auto' from the
    catalog default while another part reports the named default as failed."""
    from hearth.registry import UnregisteredDefaultModelError

    monkeypatch.setenv("HEARTH_DEFAULT_MODEL", "nope/typo-model")
    with pytest.raises(UnregisteredDefaultModelError, match="nope/typo-model"):
        _app(tmp_path, local_policy, warmup=True)
    assert fake.loads == []  # the catalog default was NOT quietly loaded in its place


def test_the_disk_probe_needs_a_real_path_and_never_downloads(tmp_path, monkeypatch):
    seen: list[object] = []

    def resolver(model_id, allow_downloads=None):
        seen.append(allow_downloads)
        return str(tmp_path) if model_id == "here" else f"/nonexistent/{model_id}"

    monkeypatch.setattr(mlx_mod, "resolve_local_model", resolver)
    assert providers_pkg._locate_on_disk("here") == str(tmp_path)
    # A bare id handed back (no huggingface_hub) is not evidence of weights on disk.
    with pytest.raises(ModelNotOnDiskError):
        providers_pkg._locate_on_disk("gone")
    assert seen == [False, False]  # a readiness probe is never a download


def test_manager_records_load_outcomes_across_eviction():
    class P:
        def __init__(self, fail=False):
            self.fail = fail
            self.is_loaded = False

        def footprint(self, model_id):
            from hearth.providers.base import ResourceEstimate

            return ResourceEstimate(ram_gb=4.0)

        def load(self, model_id):
            if self.fail:
                raise RuntimeError("boom")
            self.is_loaded = True

        def unload(self, model_id):
            self.is_loaded = False

    failing = {"bad"}
    from hearth.serving import ModelManager

    manager = ModelManager(lambda m: P(fail=m in failing), ram_ceiling_gb=5.0)
    manager.get("a")
    manager.get("b")  # evicts a
    assert manager.resident_ids() == ["b"]
    assert manager.loaded_once("a") and manager.last_load_error("a") is None
    with pytest.raises(RuntimeError):
        manager.get("bad")
    assert manager.last_load_error("bad") == "RuntimeError: boom"
    assert not manager.loaded_once("bad")
    failing.clear()
    manager.get("bad")
    assert manager.last_load_error("bad") is None and manager.loaded_once("bad")


def test_admin_models_reads_residency_off_the_providers(fake, tmp_path, local_policy):
    app, _, _ = _app(tmp_path, local_policy)
    client = TestClient(app)
    _chat(client, SMALL)
    _chat(client, SMALL)
    view = client.get("/v1/hearth/admin/models").json()
    (entry,) = view["resident"]
    assert entry["model"] == SMALL and entry["provider_model"] == SMALL
    assert entry["loaded"] is True
    assert entry["loaded_path"] == weights(SMALL)
    assert entry["generations"] == 2


# -- /v1/models lists exactly what a chat request can be served by ---------------------------


def test_v1_models_lists_only_what_the_pool_serves_and_each_listed_id_is_served(
    fake, tmp_path, local_policy
):
    """OpenAI clients and /chat build their picker from /v1/models; every entry must be
    servable and nothing servable may be missing. Asserted by REQUESTING each listed id."""
    app, _, _ = _app(tmp_path, local_policy)
    client = TestClient(app)
    ids = [m["id"] for m in client.get("/v1/models").json()["data"]]
    assert "echo" not in ids and EMBED not in ids
    assert set(ids) == {
        e.id for e in get_registry().list() if e.backend == "mlx" and "chat" in e.capabilities
    }
    for model in ids:
        assert _chat(client, model).json()["choices"][0]["message"]["content"] == tag(model)
    for unlisted in ("echo", EMBED):
        assert _chat(client, unlisted).status_code == 404

