"""One provider per model id, so the model a request names is the model that answers.

:class:`~hearth.providers.mlx.MLXProvider` holds exactly one model's weights. Before this
module the gateway's :class:`~hearth.serving.ModelManager` factory returned *the same*
provider for every id, so the /chat model dropdown, the ``model`` field of
``/v1/chat/completions`` and ``/v1/hearth/agent``, and every per-class ``local_model`` rung of
a routing ladder were all generated by the default model — while the streaming telemetry
reported the model that had been *asked for*. The check (what the request named) and the
checked thing (which weights ran) were different objects: ``CLAUDE.md`` §3.

:class:`ModelPool` is the local provider the router sees. It

* validates every id against the model registry (``config/models.yaml``): an unknown id, a
  non-chat entry, or an entry for another backend raises :class:`UnknownModelError` — never a
  silent fallback to the default. ``"auto"``/empty resolve to the registry default (the router
  has already applied the per-class ladder by the time a request arrives here);
* keeps one provider per model id — and one per (model, LoRA adapter) variant, each a full
  base reload sized at the model's ``ram_gb`` (B-069) — resident in a
  :class:`~hearth.serving.ModelManager`, LRU under ``settings.ram_ceiling_gb``;
* runs residency lookup, loading, eviction *and* generation inside a single job on the
  process's one MLX thread (``providers/mlx.py``). Because that thread runs one job at a
  time, a model cannot be evicted between being picked for a request and generating it — and
  MLX's thread-local GPU stream sees every load and every generation on the same thread.

Telemetry never comes from here: :class:`~hearth.providers.base.GenResult.model` and the
terminal :class:`~hearth.providers.base.StreamDelta.model` are filled in by the provider
instance that generated.
"""

from __future__ import annotations

import errno
import re
from collections.abc import Callable, Iterator
from dataclasses import replace
from pathlib import Path

from ..providers.base import (
    Capabilities,
    GenerationCancelledError,
    GenRequest,
    GenResult,
    ModelProvider,
    ResourceEstimate,
    StreamDelta,
    iter_stream,
    raise_if_cancelled,
)
from ..providers.mlx import (
    ModelNotOnDiskError,
    iterate_on_mlx_thread,
    run_on_mlx_thread,
    variant_key,
)
from .manager import ModelManager, ModelTooLargeError

AUTO_MODEL_IDS = ("", "auto")


class UnknownModelError(LookupError):
    """A request named a model this server cannot serve (maps to OpenAI's 404).

    ``model_id`` is the id that was asked for; the message names what *is* servable so the
    caller can fix the request rather than guess.
    """

    def __init__(self, model_id: str, message: str) -> None:
        super().__init__(message)
        self.model_id = model_id

    def __str__(self) -> str:  # LookupError would repr() a single arg; keep it readable
        return str(self.args[0])


class AdapterLoadFailedError(RuntimeError):
    """A (model, adapter) variant whose last load failed, refused without loading again.

    Raised in place of a reload until the adapter's files change (B-102). The router's
    degrade-and-retry then serves base weights, exactly as after the original failure — but
    without evicting the resident base for a load already known to fail.
    """


def adapter_fingerprint(path: str) -> tuple | None:
    """What identifies the adapter at ``path`` on disk: (relpath, mtime, ctime, inode, size).

    ``None`` when the path does not exist. Any rewrite of the adapter (a retrain, a fixed
    file, a file added or removed) changes it; a failed load is remembered only for the
    fingerprint it failed with. ``mtime`` and ``size`` alone missed a same-size overwrite
    that put the old mtime back (``cp -p``, ``rsync -t``, ``os.utime``): the fixed adapter
    stayed refused until restart (B-127). ``ctime`` cannot be set back from user space and
    changes on every write or ``utime``; the inode changes when a file is replaced by
    rename (an atomic save).
    """
    root = Path(path).expanduser()
    try:
        st = root.stat()
    except OSError:
        return None
    entries = [("", *_stamp(st))]
    if root.is_dir():
        for child in sorted(root.rglob("*")):
            try:
                cst = child.stat()
            except OSError:
                continue
            entries.append((str(child.relative_to(root)), *_stamp(cst)))
    return tuple(entries)


def _stamp(st) -> tuple[int, int, int, int]:
    return (st.st_mtime_ns, st.st_ctime_ns, st.st_ino, st.st_size)


# Load failures that say nothing about the adapter's files (B-127): the machine was out of
# memory, or the GPU refused an allocation, at that moment. Remembering one would refuse a
# good adapter until its files changed or the server restarted. MLX reports Metal failures
# as RuntimeError text ("[metal::malloc] ...", "[METAL] Command buffer execution failed:
# Insufficient Memory"), so they are recognised by message.
_TRANSIENT_MESSAGE = re.compile(
    r"\[metal|out of memory|insufficient memory|failed to allocate|cannot allocate memory"
    r"|resource exhausted|allocation failed",
    re.IGNORECASE,
)
_TRANSIENT_ERRNOS = frozenset({errno.ENOMEM, errno.EAGAIN, errno.EMFILE, errno.ENFILE})


def is_transient_load_error(exc: BaseException) -> bool:
    """Is ``exc`` a load failure of the moment (memory, GPU) rather than of the adapter?"""
    if isinstance(exc, (MemoryError, ModelTooLargeError)):
        return True
    if isinstance(exc, OSError) and exc.errno in _TRANSIENT_ERRNOS:
        return True
    return bool(_TRANSIENT_MESSAGE.search(str(exc)))


def servable_ids(registry, backend: str | None) -> list[str]:
    """Chat-capable registry ids that ``backend`` can serve (all backends when ``None``)."""
    return [
        e.id
        for e in registry.list()
        if "chat" in e.capabilities and (backend is None or e.backend == backend)
    ]


def resolve_model_id(registry, model_id: str | None, backend: str | None) -> str:
    """Resolve a requested model id to a concrete, servable registry id — or refuse.

    ``"auto"``/empty/``None`` mean the registry default — through ``require_default``, so
    an explicitly set ``HEARTH_DEFAULT_MODEL`` that names no registered model raises
    :class:`~hearth.registry.UnregisteredDefaultModelError` HERE, where the model is chosen,
    instead of quietly resolving to the catalog default (B-070: the B-047 refusal used to
    live only at CLI call sites, so example scripts and direct API users were answered by a
    model they had not named). ``backend=None`` checks membership and chat capability only
    (used where the serving backend is not a registry backend, e.g. an injected test
    provider).
    """
    wanted = registry.require_default() if model_id in (None, *AUTO_MODEL_IDS) else model_id
    entry = registry.get(wanted)
    known = servable_ids(registry, backend)
    if entry is None:
        raise UnknownModelError(
            wanted,
            f"The model {wanted!r} does not exist in the HEARTH model registry "
            f"(config/models.yaml). Servable models: {known}",
        )
    if "chat" not in entry.capabilities:
        raise UnknownModelError(
            wanted,
            f"The model {wanted!r} is registered with capabilities {entry.capabilities}, "
            f"not chat. Servable models: {known}",
        )
    if backend is not None and entry.backend != backend:
        raise UnknownModelError(
            wanted,
            f"The model {wanted!r} is served by the {entry.backend!r} backend, but this "
            f"server runs {backend!r}. Servable models: {known}",
        )
    return entry.id


def servable_for(local: ModelProvider, registry) -> list[str]:
    """The ids a chat request can name and be served by ``local`` — what /v1/models lists.

    Mirrors :func:`check_model` exactly, so the list and the 404 cannot disagree: a
    :class:`ModelPool` serves the chat models of its own backend; any other local provider
    (echo, a plugin, a test fake) answers every registered chat id itself.
    """
    own = getattr(local, "servable_ids", None)
    if callable(own):
        return own()
    return servable_ids(registry, None)


def check_model(local: ModelProvider, registry, model: str | None) -> str:
    """Validate a requested model id BEFORE anything is generated or streamed.

    A :class:`ModelPool` validates against the registry and its backend. Any other local
    provider (echo, a plugin, a test fake) serves every id itself, so the id need only be a
    registered chat model — or ``auto``. Raises :class:`UnknownModelError`; never
    substitutes the default. Shared by the gateway routes and the CLI.
    """
    resolve = getattr(local, "resolve", None)
    if callable(resolve):
        return resolve(model)
    if model in (None, *AUTO_MODEL_IDS):
        return model or "auto"
    return resolve_model_id(registry, model, backend=None)


class ModelPool:
    """A :class:`~hearth.providers.base.ModelProvider` that dispatches on ``req.model``.

    ``factory(model_id, ram_gb)`` builds the provider for one model; the pool owns
    validation, the manager owns residency. Every manager operation goes through the MLX
    thread (see the module docstring) — never call ``self.manager.get`` directly from
    another thread with a provider whose ``load`` itself hops to the MLX thread.
    """

    def __init__(
        self,
        factory: Callable[[str, float], ModelProvider],
        *,
        backend: str = "mlx",
        ram_ceiling_gb: float,
        registry=None,
        locate: Callable[[str], object] | None = None,
    ) -> None:
        self.name = backend
        self._backend = backend
        self._registry = registry
        self._factory = factory
        # ``locate(model_id)`` resolves a model's weights on disk WITHOUT loading them (and
        # without downloading), raising when they are absent. Readiness uses it so a server
        # whose default was evicted — or never loaded because warmup is off — can still say
        # truthfully whether the default can be loaded. ``None``: this pool cannot tell.
        self._locate = locate
        # manager key -> (model id, adapter path) for adapter variants (see _key).
        self._variants: dict[str, tuple[str, str]] = {}
        # variant key -> (adapter fingerprint, error) of its last FAILED load (B-102). Only
        # touched on the MLX thread, inside the jobs that call the manager.
        self._failed_variants: dict[str, tuple[tuple | None, str]] = {}
        self.manager = ModelManager(self._make, ram_ceiling_gb=ram_ceiling_gb)

    # -- registry ------------------------------------------------------------------------

    @property
    def registry(self):
        if self._registry is not None:
            return self._registry
        from ..registry import get_registry

        return get_registry()

    def resolve(self, model_id: str | None) -> str:
        """The concrete servable id for ``model_id`` (raises :class:`UnknownModelError`)."""
        return resolve_model_id(self.registry, model_id, self._backend)

    def servable_ids(self) -> list[str]:
        """Every id :meth:`resolve` accepts other than ``auto``: chat models of this backend."""
        return servable_ids(self.registry, self._backend)

    def _make(self, key: str) -> ModelProvider:
        model_id, adapter = self._variants.get(key, (key, None))
        entry = self.registry.get(model_id)
        provider = self._factory(model_id, entry.ram_gb if entry is not None else 4.5)
        if adapter is not None:
            # The provider's own default variant (MLXProvider.adapter): it loads base+adapter
            # as its ONE set of weights and is sized at the model's full ram_gb (B-069).
            provider.adapter = adapter
        return provider

    def _key(self, model_id: str, adapter: str | None) -> str:
        """The manager key for ``model_id`` with ``adapter`` layered over it.

        Every adapter variant is its own resident (B-069). mlx_lm materialises base+adapter
        as a full model per variant, so a 14B serving three adapters holds four 14Bs of
        weights; keyed together under one id the manager counted 9 GB for ~36 GB, never
        evicted a variant, and never refused one. As separate residents each is sized,
        LRU-evicted and refused like any model. (Sharing base weights is not done: mlx_lm's
        ``remove_lora_layers`` restores only plain ``LoRALinear`` layers — a DoRA/embedding/
        full-weight adapter could not be cleanly swapped out, and a leftover adapter would
        answer with weights nobody asked for.) The base model keeps the bare id, so
        readiness and the admin view address it exactly as before.
        """
        key = variant_key(model_id, adapter)
        if adapter:
            self._variants.setdefault(key, (model_id, adapter))
        return key

    # -- residency -----------------------------------------------------------------------

    def _get(self, key: str) -> ModelProvider:
        """``manager.get(key)``, refusing a variant whose last load failed (MLX thread only).

        A bad adapter used to cost a full reload per request: the variant's admission
        evicted the resident base to make room, its load failed, and the router's retry on
        base weights reloaded the base — every request, forever (B-102). A failed variant
        load is now remembered against the adapter's on-disk fingerprint and refused with
        :class:`AdapterLoadFailedError` (nothing evicted, nothing loaded) until the adapter
        changes. A base that is not on disk is not the adapter's fault and is not
        remembered; neither is a cancellation, nor a transient memory / GPU failure
        (:func:`is_transient_load_error`, B-127).
        """
        variant = self._variants.get(key)
        if variant is None:
            return self.manager.get(key)
        stamp = adapter_fingerprint(variant[1])
        failed = self._failed_variants.get(key)
        if failed is not None:
            if failed[0] == stamp:
                raise AdapterLoadFailedError(
                    f"adapter {variant[1]!r} over {variant[0]!r} failed to load before "
                    f"({failed[1]}); not retried until its files change"
                )
            del self._failed_variants[key]  # the adapter changed: worth one more load
        try:
            return self.manager.get(key)
        except (GenerationCancelledError, ModelNotOnDiskError):
            raise
        except Exception as exc:
            # A failure of the moment (out of memory, a Metal allocation) is not the
            # adapter's fault and must not refuse it until restart (B-127); nor is a model
            # too large for the ceiling (a property of the base, raised before anything is
            # evicted, so retrying it costs nothing). Only a failure that would recur on the
            # same adapter files is remembered.
            if not is_transient_load_error(exc):
                self._failed_variants[key] = (stamp, f"{type(exc).__name__}: {exc}")
            raise

    def provider_for(self, model_id: str | None) -> ModelProvider:
        """Load (if needed) and return the provider serving ``model_id``."""
        resolved = self.resolve(model_id)
        return run_on_mlx_thread(self.manager.get, resolved)

    def warm(self, model_id: str | None = None, *, only_if_fits: bool = False):
        """Load ``model_id`` (default: the registry default) now — warmup/readiness.

        ``only_if_fits``: load only if it fits beside the residents without evicting, and
        return ``None`` otherwise — checked and loaded in one job on the MLX thread under
        the manager's load lock, so no request's load can land in between (B-110).
        """
        if not only_if_fits:
            return self.provider_for(model_id)
        resolved = self.resolve(model_id)
        return run_on_mlx_thread(self.manager.get_if_fits, resolved)

    def evict(self, model_id: str) -> bool:
        """Evict ``model_id`` AND every adapter variant layered over it (B-107).

        Each variant is a full copy of the base's weights (B-069), so evicting only the bare
        id left e.g. a 9 GB 14B+adapter resident after "evict the 14B". An exact variant key
        evicts just that variant. Returns whether anything was resident.
        """

        def job() -> bool:
            keys = [model_id] + [
                key for key, (base, _adapter) in self._variants.items() if base == model_id
            ]
            evicted = [self.manager.evict(key) for key in keys]
            return any(evicted)

        return run_on_mlx_thread(job)

    @property
    def can_locate(self) -> bool:
        """Whether :meth:`weights_problem` actually checks the disk."""
        return self._locate is not None

    def weights_problem(self, model_id: str) -> str | None:
        """Why ``model_id``'s weights do not resolve on disk, or ``None`` if they do.

        Also ``None`` when this pool has no ``locate`` (it cannot tell) — callers must check
        :attr:`can_locate` before treating ``None`` as "on disk".
        """
        if self._locate is None:
            return None
        try:
            self._locate(model_id)
        except Exception as exc:  # noqa: BLE001 — any failure to resolve is "not loadable"
            return f"{type(exc).__name__}: {exc}"
        return None

    # -- the provider contract -------------------------------------------------------------

    def capabilities(self) -> Capabilities:
        return Capabilities(chat=True, embed=False, stream=True, adapters=True)

    def footprint(self, model_id: str) -> ResourceEstimate:
        entry = self.registry.get(self.resolve(model_id))
        return ResourceEstimate(ram_gb=entry.ram_gb if entry is not None else 0.0)

    def generate(self, req: GenRequest) -> GenResult:
        resolved = self.resolve(req.model)
        concrete = replace(req, model=resolved)
        key = self._key(resolved, req.adapter)

        def job() -> GenResult:
            raise_if_cancelled()  # abandoned while queued: do not load weights for it
            return self._get(key).generate(concrete)

        return run_on_mlx_thread(job)

    def stream_deltas(self, req: GenRequest) -> Iterator[StreamDelta]:
        # Resolve eagerly: an unknown id raises here, before a caller has started a response.
        resolved = self.resolve(req.model)
        concrete = replace(req, model=resolved)
        key = self._key(resolved, req.adapter)

        def make() -> Iterator[StreamDelta]:
            # Same guard as generate(): a stream abandoned while queued behind another job
            # loads nothing. Without it the provider's own check ran only after
            # manager.get() had already loaded (and possibly evicted for) the weights.
            raise_if_cancelled()
            return iter_stream(self._get(key), concrete)

        return iterate_on_mlx_thread(make)

    def stream(self, req: GenRequest) -> Iterator[str]:
        for delta in self.stream_deltas(req):
            if delta.text:
                yield delta.text


__all__ = [
    "AUTO_MODEL_IDS",
    "AdapterLoadFailedError",
    "adapter_fingerprint",
    "is_transient_load_error",
    "ModelPool",
    "check_model",
    "UnknownModelError",
    "resolve_model_id",
    "servable_for",
    "servable_ids",
]
