"""Provider registry and selection.

Selection logic: honor ``HEARTH_BACKEND`` (``auto`` | ``mlx`` | ``echo`` | a plugin name).
``auto`` prefers MLX when importable and falls back to the echo stub otherwise, so the
server always starts. The MLX backend is a :class:`~hearth.serving.ModelPool` — one
:class:`MLXProvider` per registry model id, LRU-resident under ``settings.ram_ceiling_gb`` —
so a request (or a routing-ladder rung) naming a model is generated by that model, and an
id outside the registry is refused rather than answered by the default (ARCHITECTURE §5).
Any other value is resolved against the ``hearth.providers`` plugin entry-point group
(Phase 7), so a third-party backend serves via ``HEARTH_BACKEND=<plugin-name>`` with zero
core edits.
"""

from __future__ import annotations

from pathlib import Path

from ..config import Settings, get_settings
from . import mlx as _mlx
from .base import ModelProvider
from .echo import EchoProvider
from .mlx import MLXProvider, mlx_available


def _locate_on_disk(model_id: str) -> str:
    """Resolve ``model_id``'s weights on disk only — never a download (readiness probe).

    Looked up on the module at call time so a patched resolver (tests) is the one used.
    The returned path must exist: without huggingface_hub the resolver hands back the bare
    id (leaving the error to mlx_lm), which is not evidence of weights on disk.
    """
    path = _mlx.resolve_local_model(model_id, allow_downloads=False)
    if not Path(path).expanduser().exists():
        raise _mlx.ModelNotOnDiskError(f"weights for {model_id!r} resolved to {path!r}, "
                                       "which does not exist")
    return path


def mlx_pool(settings: Settings | None = None):
    """The MLX backend: a :class:`~hearth.serving.ModelPool` of per-model providers."""
    from ..serving import ModelPool  # deferred: serving imports providers

    settings = settings or get_settings()
    return ModelPool(
        lambda model_id, ram_gb: MLXProvider(model_id, ram_gb=ram_gb),
        backend="mlx",
        ram_ceiling_gb=settings.ram_ceiling_gb,
        locate=_locate_on_disk,
    )


def select_provider(settings: Settings | None = None) -> ModelProvider:
    """Return the active provider for this process based on configuration."""
    settings = settings or get_settings()
    choice = settings.backend.lower()

    if choice == "echo":
        return EchoProvider()
    if choice == "mlx" or (choice == "auto" and mlx_available()):
        return mlx_pool(settings)
    if choice == "auto":
        return EchoProvider()

    # Fall through to a plugin-provided backend registered under `hearth.providers`.
    # Match the entry-point name as configured (case-sensitive), not the lowercased form.
    from ..plugins import PROVIDER_GROUP, load_plugin

    plugin = load_plugin(PROVIDER_GROUP, settings.backend)
    if plugin is not None:
        return plugin
    raise ValueError(
        f"Unknown HEARTH_BACKEND: {settings.backend!r} "
        "(use auto|mlx|echo, or install a plugin registering this name under hearth.providers)"
    )


__all__ = ["mlx_pool", "select_provider", "EchoProvider", "MLXProvider", "ModelProvider"]
