"""MLX inference provider — the real Apple Silicon backend (ADR-003).

Wraps ``mlx-lm``. Import of the heavy dependency is deferred to load time so that the
package (and the echo-backed skeleton) works without the ``mlx`` extra installed.
Install it with: ``uv sync --extra mlx --extra mcp --extra dev --extra files``.
"""

from __future__ import annotations

import logging
import os
import queue
import threading
from collections.abc import Callable, Iterable, Iterator, Mapping
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import TypeVar

from ..config import get_settings
from .base import (
    FINISH_STOP,
    Capabilities,
    FinishReason,
    GenRequest,
    GenResult,
    ResourceEstimate,
    StreamDelta,
    normalize_finish_reason,
)

T = TypeVar("T")

logger = logging.getLogger("hearth.providers.mlx")

# MLX's GPU stream is thread-local: weights loaded on one thread cannot be run from another
# ("There is no Stream(gpu, 0) in current thread"). FastAPI runs sync handlers on a pool of
# threads, so before this every MLX call ran on whichever pool thread took the request —
# measured against a live 14B, three concurrent /v1/chat/completions gave two 503s and one
# answer. All MLX work in the process therefore runs on this ONE thread, whoever calls it
# (gateway, agent, MCP, RAG). It also serializes the GPU, which is the honest model of one
# GPU, and stops two requests racing on the provider's active-adapter state.
_MLX_THREAD = threading.local()


def _mark_mlx_thread() -> None:
    _MLX_THREAD.active = True


_MLX_EXECUTOR = ThreadPoolExecutor(
    max_workers=1, thread_name_prefix="hearth-mlx", initializer=_mark_mlx_thread
)
_END = object()


def on_mlx_thread() -> bool:
    """True when the caller is already the process's MLX thread."""
    return getattr(_MLX_THREAD, "active", False)


def run_on_mlx_thread(fn: Callable[..., T], *args, **kwargs) -> T:
    """Run ``fn`` on the MLX thread and return its result (re-raising its exception)."""
    if on_mlx_thread():  # re-entrant: submitting to our own single worker would deadlock
        return fn(*args, **kwargs)
    return _MLX_EXECUTOR.submit(fn, *args, **kwargs).result()


def iterate_on_mlx_thread(make: Callable[[], Iterator[T]]) -> Iterator[T]:
    """Drive the iterator ``make()`` returns on the MLX thread, yielding on the caller's.

    Items cross over a queue, so a streaming response still streams. If the consumer stops
    early (a client disconnects mid-answer) the worker sees the cancellation at the next
    item and closes the generator, rather than generating to ``max_tokens`` while every
    other request waits behind it.
    """
    if on_mlx_thread():
        yield from make()
        return
    out: queue.Queue = queue.Queue()
    cancelled = threading.Event()

    def pump() -> None:
        try:
            iterator = make()
            try:
                for item in iterator:
                    if cancelled.is_set():
                        return
                    out.put((True, item))
            finally:
                close = getattr(iterator, "close", None)
                if close is not None:
                    close()
            out.put((True, _END))
        except BaseException as exc:  # noqa: BLE001 — re-raised on the consumer's thread
            out.put((False, exc))

    _MLX_EXECUTOR.submit(pump)
    try:
        while True:
            ok, item = out.get()
            if not ok:
                raise item
            if item is _END:
                return
            yield item
    finally:
        cancelled.set()


class MLXUnavailableError(RuntimeError):
    """Raised when the MLX backend is requested but ``mlx-lm`` isn't importable."""


def mlx_available() -> bool:
    """True if ``mlx-lm`` can be imported in this environment."""
    import importlib.util

    return importlib.util.find_spec("mlx_lm") is not None


class ModelNotOnDiskError(RuntimeError):
    """Raised when a model would have to be downloaded to load, and downloads are off.

    ``models_dir`` is HEARTH's own models directory the resolver looked in (``None`` when
    raised elsewhere), so a report can name the directory actually searched instead of
    re-deriving it (``hearth doctor --offline`` under a custom ``HEARTH_HOME``).
    """

    def __init__(self, message: str, models_dir: Path | None = None) -> None:
        super().__init__(message)
        self.models_dir = models_dir


class ModelMismatchError(RuntimeError):
    """Raised when a provider bound to one model is asked to serve a different one.

    An :class:`MLXProvider` holds exactly one model's weights. Before this check, a request
    naming any other model was generated by the bound weights anyway — the /chat dropdown,
    the ``model`` field and every per-class ladder rung silently ran the default model. A
    request is now either served by the model it names or refused; multi-model serving goes
    through :class:`hearth.serving.ModelPool`, which holds one provider per model id.
    """


def resolve_local_model(model_id: str, allow_downloads: bool | None = None) -> str:
    """Return a local path for ``model_id``, never touching the network unless allowed.

    ``hearth models pull`` downloads into ``settings.models_dir`` (``~/.hearth/models``),
    but ``mlx_lm.load`` asks huggingface_hub, which resolves ``HF_HUB_CACHE`` ->
    ``HF_HOME/hub`` -> ``~/.cache/huggingface/hub`` and knows nothing about HEARTH. The two
    halves never agreed: a freshly pulled model was invisible to the provider unless the
    operator happened to export ``HF_HUB_CACHE`` themselves, so ``hearth models pull X``
    followed by a run would report X missing — or quietly serve a *different* model that
    happened to sit in the default cache.

    Resolution order: an existing filesystem path, as-is; HEARTH's own directory; then the
    huggingface_hub cache (its normal ``HF_HUB_CACHE`` -> ``HF_HOME/hub`` -> default order).
    Both cache lookups are ``local_files_only``. Handing ``mlx_lm.load`` a bare repo id is
    what used to reach huggingface.co — it calls ``snapshot_download`` with the network on,
    on every load — so a model in neither place raises :class:`ModelNotOnDiskError` unless
    ``allow_downloads`` (default ``settings.allow_downloads``, ``HEARTH_ALLOW_DOWNLOADS``)
    is set. A load is never a download by accident.

    Resolution is explicit rather than by mutating ``os.environ`` (e.g. ``HF_HUB_OFFLINE``):
    a hidden global would make this module disagree with anything that inspects the
    environment (such as ``scripts/hearth_status.py``), which is the class of bug this is
    fixing.
    """
    settings = get_settings()
    allow_downloads = downloads_allowed(allow_downloads)
    candidate = Path(model_id).expanduser()
    if candidate.exists():
        return str(candidate)
    try:  # deferred: huggingface_hub is only present with the mlx/embeddings extras
        from huggingface_hub import snapshot_download
        from huggingface_hub.errors import HFValidationError, LocalEntryNotFoundError
    except ImportError:
        # No hub client means mlx_lm cannot download either; let its own error speak.
        return model_id
    models_dir = settings.models_dir
    cache_dirs = ([str(models_dir)] if models_dir.is_dir() else []) + [None]
    not_a_repo_id = False
    for cache_dir in cache_dirs:  # None = huggingface_hub's own cache resolution
        try:
            return snapshot_download(
                repo_id=model_id, cache_dir=cache_dir, local_files_only=True
            )
        # Exactly the two "not here" outcomes of a local-only lookup: not cached, or not a
        # repo id at all. Anything else — a network error, a blocked socket — is NOT a cache
        # miss and must surface: swallowing it would let a resolver that reached for the
        # network still end in ModelNotOnDiskError and read as disk-only.
        except LocalEntryNotFoundError:
            continue
        except HFValidationError:
            not_a_repo_id = True
            continue
    if allow_downloads:
        return model_id
    raise ModelNotOnDiskError(
        _not_on_disk_message(model_id, models_dir, not_a_repo_id), models_dir=models_dir
    )


def _not_on_disk_message(model_id: str, models_dir: Path, not_a_repo_id: bool) -> str:
    """The ModelNotOnDiskError text, with the fix that works for THIS kind of id.

    ``hearth models pull`` accepts registry ids only, so telling the operator to pull a
    filesystem path or an unregistered repo id sent them to a command that answers
    "Unknown model id". Three cases: a path (no such path; nothing to pull), a registry
    entry (pull its registry id), an unregistered repo id (register it, then pull).
    """
    looks_like_path = not_a_repo_id or model_id.startswith(("/", "~", ".")) or (
        model_id.count("/") > 1
    )
    if looks_like_path:
        return (
            f"model {model_id!r} is not on disk: no such path ({Path(model_id).expanduser()} "
            "does not exist). A filesystem path is loaded as given and nothing can be pulled "
            "for it; check the path, or name a registry id (hearth models list)."
        )
    where = (
        f"model {model_id!r} is not on disk (looked in {models_dir} and the huggingface "
        "hub cache) and HEARTH does not download on load."
    )
    entry = _registry_entry_for(model_id)
    if entry is not None:
        return f"{where} Fetch it deliberately with `hearth models pull {entry.id}`."
    return (
        f"{where} It is not in the model registry, so `hearth models pull` refuses it: "
        "register it in config/models.yaml (or your HEARTH_MODELS_YAML) with this id as its "
        f"source, then run `hearth models pull {model_id}`; or set HEARTH_ALLOW_DOWNLOADS=1 "
        "to let loads download (doctor --offline then reports UNSAFE)."
    )


def _registry_entry_for(model_id: str):
    """The registry entry whose id or download source is ``model_id``, else ``None``."""
    try:
        from ..registry import get_registry

        entries = get_registry().list()
    except Exception:  # noqa: BLE001 — a hint must never mask the not-on-disk error
        return None
    for entry in entries:
        if model_id in (entry.id, entry.source):
            return entry
    return None


def downloads_allowed(override: bool | None = None) -> bool:
    """Whether a model load may download: ``override`` if given, else
    ``settings.allow_downloads`` (``HEARTH_ALLOW_DOWNLOADS``). The one place every load
    path (serving, train, convert, export-coreml) reads the opt-in, so they cannot disagree.
    """
    return get_settings().allow_downloads if override is None else override


#: What a child process that loads weights gets when downloads are off. Both are needed:
#: huggingface_hub reads ``HF_HUB_OFFLINE``; transformers reads ``TRANSFORMERS_OFFLINE``.
OFFLINE_ENV = {"HF_HUB_OFFLINE": "1", "TRANSFORMERS_OFFLINE": "1"}


def model_load_env(
    allow_downloads: bool | None = None, base: Mapping[str, str] | None = None
) -> dict[str, str]:
    """The environment for a CHILD process that loads model weights (``mlx_lm.lora``…).

    Resolving the model id to a path (:func:`resolve_local_model`) keeps the *weights* load
    off the network, but a child library may still reach the hub for something else — a
    tokenizer file, a model card (``mlx_lm.convert`` fetches the source repo's README when
    given a repo id), a dataset. So unless downloads are opted in, the child also runs with
    the hub's own offline switches set. The parent's ``os.environ`` is copied, never
    mutated: a hidden global would make this process disagree with anything that inspects
    its environment (the bug class in CLAUDE.md §3).
    """
    allow_downloads = downloads_allowed(allow_downloads)
    env = dict(os.environ if base is None else base)
    if not allow_downloads:
        env.update(OFFLINE_ENV)
    return env


def audit_connects(fn: Callable[..., T], *args, **kwargs) -> tuple[object, list[object]]:
    """Call ``fn`` with every socket connect refused AND recorded.

    Returns ``(outcome, connect_attempts)`` where ``outcome`` is ``fn``'s return value or
    the exception it raised. The connect list is the evidence: an exception type cannot
    tell a disk-only lookup from one that tried the network, because huggingface_hub turns
    a refused connection into ``LocalEntryNotFoundError`` — the same error a plain cache
    miss raises (measured: 8 connects, then ModelNotOnDiskError). Lives here, not in
    ``hearth.status``, which may not import a networking module at all
    (tests/test_status_readonly.py). Single-threaded use only: it swaps
    ``socket.socket.connect`` for the duration.
    """
    import socket

    attempts: list[object] = []

    def refuse(self, address, *a, **kw):
        attempts.append(address)
        raise OSError(f"connect audit refused a network connect to {address!r}")

    real = (socket.socket.connect, socket.socket.connect_ex)
    socket.socket.connect = refuse
    socket.socket.connect_ex = refuse
    try:
        outcome: object = fn(*args, **kwargs)
    except Exception as exc:  # noqa: BLE001 — the outcome IS the exception; caller judges
        outcome = exc
    finally:
        socket.socket.connect, socket.socket.connect_ex = real
    return outcome, attempts


def audit_resolution(model_id: str, allow_downloads: bool) -> tuple[object, list[object]]:
    """Resolve ``model_id`` under :func:`audit_connects` — the status probe's instrument."""
    return audit_connects(resolve_local_model, model_id, allow_downloads=allow_downloads)


class MLXProvider:
    """Loads a single model via ``mlx-lm`` and serves streaming/non-streaming completions.

    The model is loaded lazily on first use and cached for the process lifetime (Phase 0
    keeps exactly one resident base model; ADR-003). LoRA adapters are hot-swappable per
    request (Phase 4): :meth:`generate`/:meth:`stream` accept an optional ``adapter`` path
    that layers over the base weights; each distinct adapter path is loaded once and cached
    alongside the base so switching between them is cheap (ARCHITECTURE §5).
    """

    name = "mlx"

    def __init__(
        self, model_id: str, adapter: str | None = None, ram_gb: float | None = None
    ) -> None:
        self.model_id = model_id
        self.adapter = adapter
        # Resident footprint used by ModelManager's RAM ceiling; the registry's ``ram_gb``
        # when the caller knows it (ModelPool passes it), else looked up in footprint().
        self._ram_gb = ram_gb
        self._model = None
        self._tokenizer = None
        # adapter path -> (model, tokenizer); the base (no adapter) is keyed by "".
        self._cache: dict[str, tuple[object, object]] = {}
        # Evidence, not configuration: the on-disk path mlx_lm.load actually read for the
        # base weights, and how many generations THIS instance has run. Readiness and the
        # admin residency view report these rather than what a request asked for.
        self.loaded_path: str | None = None
        self.generations = 0

    # -- residency (driven by ModelManager; always on the MLX thread) ------------------

    @property
    def is_loaded(self) -> bool:
        """True only when this instance currently holds base weights in memory."""
        return "" in self._cache

    def load(self, model_id: str | None = None) -> None:
        """Load the base weights now, on the MLX thread (warmup / ModelManager admission).

        Raises whatever the load raises (:class:`ModelNotOnDiskError`, a corrupt checkpoint,
        mlx-lm missing) so a caller — readiness, a request — sees the real failure.
        """
        if model_id is not None and model_id != self.model_id:
            raise ModelMismatchError(
                f"provider for {self.model_id!r} was asked to load {model_id!r}"
            )
        run_on_mlx_thread(self._load_variant, None)

    def unload(self, model_id: str | None = None) -> None:
        """Drop every cached variant and return the memory to the allocator (MLX thread)."""
        run_on_mlx_thread(self._unload_here)

    def _unload_here(self) -> None:
        self._cache.clear()
        self._model = None
        self._tokenizer = None
        self.loaded_path = None
        import gc

        gc.collect()
        try:  # return freed buffers to the OS; a no-op without the mlx extra
            import mlx.core as mx

            mx.clear_cache()
        except Exception:  # noqa: BLE001 — best-effort; eviction must not fail a load
            pass
        logger.info("unloaded %s", self.model_id)

    def capabilities(self) -> Capabilities:
        return Capabilities(chat=True, embed=False, stream=True, adapters=True)

    def _load_variant(self, adapter: str | None):
        """Load (and cache) the (model, tokenizer) for ``adapter`` (``None`` = base weights).

        A distinct ``adapter_path`` layers a LoRA adapter over the base; loaded once per
        path and cached so per-request hot-swap is a dict lookup after the first use.
        """
        key = adapter or ""
        cached = self._cache.get(key)
        if cached is not None:
            return cached
        if not mlx_available():
            raise MLXUnavailableError(
                "mlx-lm is not installed. Install the backend with: "
                "uv sync --extra mlx --extra mcp --extra dev --extra files"
            )
        from mlx_lm import load  # deferred heavy import

        kwargs = {"adapter_path": adapter} if adapter else {}
        path = resolve_local_model(self.model_id)
        loaded = load(path, **kwargs)
        self._ensure_stop_tokens(loaded[1])
        self._cache[key] = loaded
        if not adapter:
            self.loaded_path = path
        logger.info("loaded %s from %s%s", self.model_id, path,
                    f" with adapter {adapter}" if adapter else "")
        return loaded

    @staticmethod
    def _ensure_stop_tokens(tokenizer) -> None:
        """Make generation stop at the chat-template turn terminator.

        Root cause of the LoRA "ramble" (see ``_clean_stream``): mlx-lm's ``generate`` stops
        only on ``tokenizer.eos_token_ids`` — for Qwen that's ``<|endoftext|>`` (151643) — but
        the chat template ends an assistant turn with a *different* token, ``<|im_end|>``
        (151645, the tokenizer's ``eos_token``). A model that emits the turn terminator but not
        the base EOS therefore never stops: it decodes ``<|im_end|>`` to the literal string and
        runs to ``max_tokens``. Base models usually emit ``<|endoftext|>`` soon after and get
        lucky; a tuned adapter can loop the turn terminator forever. Adding ``eos_token_id`` to
        the stop set fixes it at the source — generation ends cleanly at end-of-turn (and stops
        burning tokens on the ramble). Best-effort: a tokenizer without a mutable
        ``eos_token_ids`` set is left as-is (the ``_strip_terminators`` safety net still runs).
        """
        eos_id = getattr(tokenizer, "eos_token_id", None)
        stop = getattr(tokenizer, "eos_token_ids", None)
        if eos_id is None or stop is None:
            return
        try:
            stop.add(eos_id)
        except AttributeError:
            pass

    def _ensure_loaded(self, adapter: str | None = None) -> None:
        """Ensure the variant for ``adapter`` (or the provider default) is the active one."""
        selected = adapter if adapter is not None else self.adapter
        self._model, self._tokenizer = self._load_variant(selected)

    def generate(self, req: GenRequest) -> GenResult:
        """Run a completion, reporting whether it ended at EOS or at the ``max_tokens`` cap.

        Built on :meth:`stream_deltas` rather than ``mlx_lm.generate``: the latter returns
        only the decoded string, which is exactly the information loss that let a truncated
        answer be reported as a clean stop. Runs whole on the MLX thread: it reads the
        active tokenizer after streaming, which another request could otherwise swap.
        """
        return run_on_mlx_thread(self._generate_here, req)

    def _generate_here(self, req: GenRequest) -> GenResult:
        deltas = list(self.stream_deltas(req))
        text = "".join(d.text for d in deltas).strip()
        finish_reason = next(
            (d.finish_reason for d in reversed(deltas) if d.finish_reason), FINISH_STOP
        )
        prompt = self._format_prompt(req.messages)
        return GenResult(
            text=text,
            model=self.model_id,
            backend=self.name,
            prompt_tokens=len(self._tokenizer.encode(prompt)),
            completion_tokens=len(self._tokenizer.encode(text)),
            finish_reason=finish_reason,
        )

    def stream(self, req: GenRequest) -> Iterator[str]:
        """Yield decoded text deltas as ``mlx_lm.stream_generate`` produces them.

        Chat terminators are handled exactly as in :meth:`generate`: streaming stops at the
        first terminator marker and never leaks it — a LoRA-tuned model that fails to stop at
        EOS can emit the literal marker mid-stream (see :meth:`_clean_stream`).
        """
        for delta in self.stream_deltas(req):
            if delta.text:
                yield delta.text

    def stream_deltas(self, req: GenRequest) -> Iterator[StreamDelta]:
        """Stream cleaned text deltas, then the real stop reason from ``mlx-lm``.

        ``mlx_lm.stream_generate`` tags each ``GenerationResponse`` with ``finish_reason``
        (``None`` while generating, then ``"stop"`` at an EOS token or ``"length"`` at the
        ``max_tokens`` cap); we pass that through so the gateway never has to guess. When
        :meth:`_clean_stream` cuts early at a literal terminator marker the loop ends before
        mlx-lm reports anything — that *is* an end-of-turn, so it normalizes to ``"stop"``.
        Generation runs on the process's MLX thread (:func:`iterate_on_mlx_thread`).
        """
        return iterate_on_mlx_thread(lambda: self._stream_deltas_here(req))

    def _check_model(self, req: GenRequest) -> None:
        """Refuse a request that names a different *registered* model than this one.

        ``"auto"``/empty mean "whatever this provider serves". An id outside the registry is
        left alone: tests and scripts drive a bare provider with placeholder ids, and the
        entry points (gateway, CLI, MCP) validate ids against the registry before a request
        gets here. What this stops is the real failure: a registered model — a ladder rung,
        a dropdown pick — being answered by whichever weights this instance holds.
        """
        if req.model in ("", "auto", self.model_id):
            return
        from ..registry import get_registry

        if get_registry().get(req.model) is not None:
            raise ModelMismatchError(
                f"request for model {req.model!r} reached the provider for "
                f"{self.model_id!r}; refusing to answer it with the wrong weights"
            )

    def _stream_deltas_here(self, req: GenRequest) -> Iterator[StreamDelta]:
        self._check_model(req)
        self._ensure_loaded(req.adapter)
        from mlx_lm import stream_generate

        self.generations += 1
        logger.info(
            "generating with %s (weights %s, adapter=%s, generation #%d of this instance)",
            self.model_id, self.loaded_path, req.adapter, self.generations,
        )

        prompt = self._format_prompt(req.messages)
        # Populated as responses are consumed; read after _clean_stream drains (or cuts).
        raw_reason: list[str | None] = [None]

        def chunks() -> Iterator[str]:
            for response in stream_generate(
                self._model,
                self._tokenizer,
                prompt=prompt,
                max_tokens=req.max_tokens,
            ):
                raw_reason[0] = getattr(response, "finish_reason", None)
                yield response.text

        for text in self._clean_stream(chunks()):
            yield StreamDelta(text=text)
        yield StreamDelta(
            finish_reason=self._finish_reason(raw_reason[0]), model=self.model_id
        )

    @staticmethod
    def _finish_reason(raw: str | None) -> FinishReason:
        """Normalize mlx-lm's ``finish_reason`` onto the OpenAI vocabulary."""
        return normalize_finish_reason(raw)

    def _clean_stream(self, chunks: Iterable[str]) -> Iterator[str]:
        """Yield cleaned text deltas from raw model ``chunks`` (pure; no model needed).

        Two jobs, mirroring :meth:`generate`'s cut-at-first-marker: (1) hold back a tail that
        could be the *start* of a terminator so a marker split across chunk boundaries is
        never leaked, and (2) stop emitting at the first *complete* terminator — a LoRA-tuned
        model that fails to stop at EOS emits the literal marker mid-stream and then rambles
        (``QX-2<|im_end|> !<|im_end|> ...``), and streaming clients must not see that.
        """
        pending = ""
        max_marker = max((len(m) for m in self._terminator_markers() if m), default=0)
        for chunk in chunks:
            pending += chunk
            cut = self._first_terminator(pending)
            if cut is not None:
                if cut > 0:
                    yield pending[:cut]
                return
            # No complete marker yet: emit all but a tail that could still start one.
            safe = len(pending) - max_marker
            if safe > 0:
                yield pending[:safe]
                pending = pending[safe:]
        tail = self._strip_terminators(pending)
        if tail:
            yield tail

    def footprint(self, model_id: str) -> ResourceEstimate:
        """Resident size for the RAM ceiling: the registry's ``ram_gb`` for this model.

        This used to be a flat 4.5 GB for every model, so a 14B (9 GB) and a 3B (2 GB) were
        sized identically and the ceiling could not evict on the real numbers.
        """
        if self._ram_gb is not None:
            return ResourceEstimate(ram_gb=self._ram_gb)
        from ..registry import get_registry

        entry = get_registry().get(model_id or self.model_id)
        return ResourceEstimate(ram_gb=entry.ram_gb if entry is not None else 4.5)

    def _terminator_markers(self) -> list[str]:
        markers = ["<|im_end|>", "<|endoftext|>", "<|eot_id|>"]
        eos = getattr(self._tokenizer, "eos_token", None)
        if eos:
            markers.append(eos)
        return markers

    def _first_terminator(self, text: str) -> int | None:
        """Index of the earliest terminator marker in ``text``, or ``None`` if none appear."""
        cut: int | None = None
        for m in self._terminator_markers():
            if not m:
                continue
            idx = text.find(m)
            if idx != -1:
                cut = idx if cut is None else min(cut, idx)
        return cut

    def _strip_terminators(self, text: str) -> str:
        """Cut the output at the first chat end-of-turn / EOS token emitted verbatim.

        Some chat templates decode the terminator (e.g. ``<|im_end|>``) into the output
        string instead of stopping before it. A base model usually stops at the real EOS
        token, but a LoRA-tuned model can emit the *literal* marker mid-stream and then
        ramble (``QX-2<|im_end|> !<|im_end|> ...``). Truncating at the earliest marker
        returns the clean answer in both cases (a bare trailing marker is just the special
        case where the cut is at the end).
        """
        cut = self._first_terminator(text)
        return text if cut is None else text[:cut]

    def _format_prompt(self, messages: list) -> str:
        """Render messages via the tokenizer's chat template when available."""
        chat = [{"role": m.role, "content": m.content} for m in messages]
        tmpl = getattr(self._tokenizer, "apply_chat_template", None)
        if tmpl is not None:
            return tmpl(chat, tokenize=False, add_generation_prompt=True)
        # Fallback for tokenizers without a chat template.
        return "\n".join(f"{m.role}: {m.content}" for m in messages) + "\nassistant:"
